/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.login.Faculty;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.AdminPkg.Faculty;
import model.AdminPkg.StudentDirectory;
import model.CoursePkg.Course;
import model.CoursePkg.CourseCatalog;

/**
 *
 * @author Sathya
 */
public class FacultyLandingPage extends javax.swing.JPanel {

    /**
     * Creates new form FacultyLandingPage
     */
    JPanel userProcessContainer;
    StudentDirectory studentDir;
    Faculty faculty;
    CourseCatalog courseCatalog;

    public FacultyLandingPage(JPanel userProcessContainer, StudentDirectory studentDir, Faculty faculty, CourseCatalog courseCatalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.courseCatalog = courseCatalog;
        this.faculty = faculty;
        this.studentDir = studentDir;
        welcomeLbl.setText(faculty.getFull_name());
        ratingTextArea.setText("Your rating : " + faculty.getRating());
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        profSpecTable = new javax.swing.JTable();
        ratingTextArea = new javax.swing.JLabel();
        createCourseBtn = new javax.swing.JButton();
        editCourseBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        manageScheduleBtn = new javax.swing.JButton();
        btnViewProfileDetails = new javax.swing.JButton();
        viewEmpFeedBackBtn = new javax.swing.JButton();

        jLabel1.setText("Welcome");

        profSpecTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Region", "Language"
            }
        ));
        jScrollPane1.setViewportView(profSpecTable);

        createCourseBtn.setText("Create Course");
        createCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCourseBtnActionPerformed(evt);
            }
        });

        editCourseBtn.setText("Edit Course");
        editCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCourseBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        manageScheduleBtn.setText("Manage Schedules");
        manageScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageScheduleBtnActionPerformed(evt);
            }
        });

        btnViewProfileDetails.setText("View Profile Details");
        btnViewProfileDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileDetailsActionPerformed(evt);
            }
        });

        viewEmpFeedBackBtn.setText("View Employer Feedbacks");
        viewEmpFeedBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEmpFeedBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createCourseBtn)
                        .addGap(44, 44, 44)
                        .addComponent(editCourseBtn)
                        .addGap(45, 45, 45)
                        .addComponent(manageScheduleBtn)
                        .addGap(44, 44, 44)
                        .addComponent(viewEmpFeedBackBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(refreshBtn)
                                        .addGap(36, 36, 36)
                                        .addComponent(ratingTextArea))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnViewProfileDetails)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(204, 204, 204))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(ratingTextArea)
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewProfileDetails)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(welcomeLbl))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(refreshBtn)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createCourseBtn)
                    .addComponent(editCourseBtn)
                    .addComponent(manageScheduleBtn)
                    .addComponent(viewEmpFeedBackBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(145, 145, 145))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void createCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCourseBtnActionPerformed
        // TODO add your handling code here:
        CreateCourseJPanel createCourseJPanel = new CreateCourseJPanel(userProcessContainer, studentDir, faculty, courseCatalog);
        userProcessContainer.add("createCourseJPanel", createCourseJPanel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_createCourseBtnActionPerformed

    private void editCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCourseBtnActionPerformed
        // TODO add your handling code here:

        int selectedRow = profSpecTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a course to edit details", "Warning", JOptionPane.ERROR_MESSAGE);
        } else {
            Course course = (Course) profSpecTable.getValueAt(selectedRow, 0);
            EditCourseJPanel editCourseJPanel = new EditCourseJPanel(userProcessContainer, course);
            userProcessContainer.add("EditCourseJPanel", editCourseJPanel);
            ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
        }

    }//GEN-LAST:event_editCourseBtnActionPerformed

    private void manageScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageScheduleBtnActionPerformed
        // TODO add your handling code here:
        ManageScheduleJPanel manageSchedulePanel = new ManageScheduleJPanel(userProcessContainer, studentDir, faculty);
        this.userProcessContainer.add("manageSchedulePanel", manageSchedulePanel);
        ((CardLayout) this.userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_manageScheduleBtnActionPerformed

    private void btnViewProfileDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileDetailsActionPerformed
        // TODO add your handling code here:
        ViewFacultyProfileJPanel viewFacultyProfileJPanel = new ViewFacultyProfileJPanel(userProcessContainer, faculty);
        this.userProcessContainer.add("ViewFacultyProfileJPanel", viewFacultyProfileJPanel);
        ((CardLayout) this.userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnViewProfileDetailsActionPerformed

    private void viewEmpFeedBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEmpFeedBackBtnActionPerformed
        // TODO add your handling code here:
        ViewEmpFeedbackJPanel viewEmpFeedbackJPanel = new ViewEmpFeedbackJPanel(userProcessContainer, faculty);
        this.userProcessContainer.add("viewEmpFeedbackJPanel",viewEmpFeedbackJPanel);
        ((CardLayout)this.userProcessContainer.getLayout()).next(this.userProcessContainer);
    }//GEN-LAST:event_viewEmpFeedBackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnViewProfileDetails;
    private javax.swing.JButton createCourseBtn;
    private javax.swing.JButton editCourseBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton manageScheduleBtn;
    private javax.swing.JTable profSpecTable;
    private javax.swing.JLabel ratingTextArea;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton viewEmpFeedBackBtn;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) profSpecTable.getModel();
        dtm.setRowCount(0);
        for (Course course : courseCatalog.getCourseList()) {
            if (course.getFaculty().getFull_name().equals(this.faculty.getFull_name())) {
                Object[] obj = new Object[4];
                obj[0] = course;
                obj[1] = course.getCourseName();
                obj[2] = course.getRegion();
                obj[3] = course.getLang();
                dtm.addRow(obj);

            }
        }
    }
}
