/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.login.Faculty;


import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.AdminPkg.FacultyDirectory;
import model.AdminPkg.StudentDirectory;
import model.CoursePkg.CourseCatalog;
import model.AdminPkg.Faculty;

/**
 *
 * @author Sathya
 */
public class FacultyLoginPage extends javax.swing.JPanel {

    /**
     * Creates new form FacultyLoginPage
     */
    
    JPanel userProcessContainer;
    StudentDirectory studentDir;
    FacultyDirectory facultyDir;
    CourseCatalog courseCatalog;
    
    public FacultyLoginPage(JPanel userProcessContainer, StudentDirectory studentDir,FacultyDirectory facultyDir,CourseCatalog courseCatalog) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.studentDir = studentDir;
        this.facultyDir = facultyDir;
        this.courseCatalog = courseCatalog;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bypassBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        facultyIdTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pwdTextField = new javax.swing.JTextField();

        bypassBtn.setText("Bypass");
        bypassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bypassBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Faculty ID :");

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("password");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bypassBtn)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(facultyIdTextField))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loginBtn)
                                .addGap(0, 96, Short.MAX_VALUE))
                            .addComponent(pwdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bypassBtn)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facultyIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(loginBtn)
                .addContainerGap(389, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        String faculty_id = facultyIdTextField.getText();
        String pwd = pwdTextField.getText();
        if(faculty_id.isBlank() || pwd.isBlank())
            JOptionPane.showMessageDialog(this, "Admin id or password is emopty","ERROR",JOptionPane.ERROR_MESSAGE);
        else{
            Faculty faculty = this.facultyDir.getFacultyByFacultyId(faculty_id);
            if(faculty!=null){
                if(faculty.getPwd().equals(pwd) && faculty.getIsAccActive()==true ){
                    FacultyLandingPage facultyLandingPage = new FacultyLandingPage(userProcessContainer,studentDir, faculty, courseCatalog);
                    this.userProcessContainer.add("facultyLandingPage", facultyLandingPage);
                    ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
                }   
                else
                    JOptionPane.showMessageDialog(this, "Faculty id or password incorrect","ERROR",JOptionPane.ERROR_MESSAGE);
            }
            

        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void bypassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bypassBtnActionPerformed
        // TODO add your handling code here:
        Faculty faculty = this.facultyDir.getFacultyByFacultyId("ftest");
        FacultyLandingPage facultyLandingPage = new FacultyLandingPage(userProcessContainer,studentDir, faculty, courseCatalog);
        this.userProcessContainer.add("facultyLandingPage", facultyLandingPage);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
        
    }//GEN-LAST:event_bypassBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bypassBtn;
    private javax.swing.JTextField facultyIdTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField pwdTextField;
    // End of variables declaration//GEN-END:variables
}
