/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.login.Student;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.AdminPkg.Faculty;
import model.AdminPkg.FacultyDirectory;
import model.AdminPkg.OECA;
import model.AdminPkg.Student;
import model.CoursePkg.Course;
import model.CoursePkg.CourseCatalog;

/**
 *
 * @author thivya
 */
public class StudentLandingPage extends javax.swing.JPanel {

    /**
     * Creates new form StudentProfileJPanel
     */
    CourseCatalog courseCatalog;
    JPanel userProcessContainer;
    FacultyDirectory facultyDir;
    Student student;
    OECA oeca;

    public StudentLandingPage(JPanel userProcessContainer, CourseCatalog courseCatalog, Student student, FacultyDirectory facultyDir, OECA oeca) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.courseCatalog = courseCatalog;
        this.student = student;
        this.oeca =oeca;
        this.facultyDir = facultyDir;
        welcomeLbl.setText(this.student.getFull_name());
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        welcomeLbl = new javax.swing.JLabel();
        btnViewProfile = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseDetails = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        scheduleAppointmentBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        reqTranscBtn = new javax.swing.JButton();
        btnDropCourses = new javax.swing.JButton();
        graduateStatusBtn = new javax.swing.JButton();

        jLabel1.setText("Welcome");

        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });

        btnBrowse.setText("Enroll or Browse Courses");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        tblCourseDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Faculty", "Region", "Language"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCourseDetails);

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        scheduleAppointmentBtn.setText("Schedule Appointment");
        scheduleAppointmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleAppointmentBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("YOUR REGISTERED COURSES");

        reqTranscBtn.setText("Request Transcript");
        reqTranscBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqTranscBtnActionPerformed(evt);
            }
        });

        btnDropCourses.setText("Drop Courses");
        btnDropCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDropCoursesActionPerformed(evt);
            }
        });

        graduateStatusBtn.setText("Check Graduate Status");
        graduateStatusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                graduateStatusBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backBtn)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnViewProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(153, 153, 153)
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBrowse)
                                        .addGap(46, 46, 46)
                                        .addComponent(scheduleAppointmentBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(231, 231, 231)
                                        .addComponent(btnDropCourses)))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(reqTranscBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(graduateStatusBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 118, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnViewProfile)
                    .addComponent(welcomeLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrowse)
                    .addComponent(scheduleAppointmentBtn)
                    .addComponent(reqTranscBtn))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDropCourses)
                    .addComponent(graduateStatusBtn))
                .addGap(31, 31, 31)
                .addComponent(backBtn)
                .addGap(66, 66, 66))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        ViewCoursesJPanel viewCoursesJPanel = new ViewCoursesJPanel(userProcessContainer, courseCatalog, student);
        userProcessContainer.add("ViewCoursesJPanel", viewCoursesJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:
        ViewStudentProfileJPanel viewStudentProfileJPanel = new ViewStudentProfileJPanel(userProcessContainer, student);
        userProcessContainer.add("ViewStudentProfileJPanel", viewStudentProfileJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewProfileActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void scheduleAppointmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleAppointmentBtnActionPerformed
        // TODO add your handling code here:
        if(!this.student.getCourseList().isEmpty()){
            int index = tblCourseDetails.getSelectedRow();
            if(index!=-1){
                DefaultTableModel dtm = (DefaultTableModel) tblCourseDetails.getModel();
                Faculty bookFaculty = ((Course)dtm.getValueAt(index, 0)).getFaculty();
                ScheduleAppointmentJPanel scheduleAppointmentJPanel = new ScheduleAppointmentJPanel(userProcessContainer,  student, bookFaculty );
                this.userProcessContainer.add("scheduleAppointmentJPanel",scheduleAppointmentJPanel);
                ((CardLayout)this.userProcessContainer.getLayout()).next(this.userProcessContainer);
            }
            else
              JOptionPane.showMessageDialog(this, "Select Course to book an appointment", "error", JOptionPane.ERROR_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(this, "Register for courses before\n booking an appointments", "error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_scheduleAppointmentBtnActionPerformed

    private void reqTranscBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqTranscBtnActionPerformed
        // TODO add your handling code here:
        TransciriptJPanel transciriptJPanel = new TransciriptJPanel(this.userProcessContainer,this.student);
        this.userProcessContainer.add("transciriptJPanel",transciriptJPanel);
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_reqTranscBtnActionPerformed

    private void btnDropCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDropCoursesActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCourseDetails.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to drop courses", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
             int index = JOptionPane.showConfirmDialog(this, "Do you want to Drop Your Course?","Info",JOptionPane.YES_NO_OPTION);
             if (index==JOptionPane.YES_OPTION) {
            Course course = (Course) tblCourseDetails.getValueAt(selectedRow, 0);
            student.deleteCourseToStudent(course);
            JOptionPane.showMessageDialog(null, "Course Sucessfully Dropped!");
        } 
        }        
    }//GEN-LAST:event_btnDropCoursesActionPerformed

    private void graduateStatusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_graduateStatusBtnActionPerformed
        // TODO add your handling code here:
        int credits = this.oeca.isReadyTOGraduate(this.student.getTranscript());
        if(credits>=32){
            JOptionPane.showMessageDialog(this, "Congradulations!. You are all set to graduate");
        }
        else{
             JOptionPane.showMessageDialog(this, "You still have " + (32-credits) +"more credits to\ncomplete this degree","ERROR", JOptionPane.ERROR_MESSAGE);
             if(this.oeca.doesStudentAlreadyGraduated(student))
                 this.oeca.removeStudentFromGradStudent(student);
        }
        
    }//GEN-LAST:event_graduateStatusBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnDropCourses;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JButton graduateStatusBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reqTranscBtn;
    private javax.swing.JButton scheduleAppointmentBtn;
    private javax.swing.JTable tblCourseDetails;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblCourseDetails.getModel();
        dtm.setRowCount(0);
        for (Course course : student.getCourseList()) {
            Object[] row = new Object[5];
            row[0] = course;
            row[1] = course.getCourseName();
            row[2] = course.getFaculty().getFull_name();
            row[3] = course.getRegion();
            row[4] = course.getLang();
            dtm.addRow(row);
        }
    }

}
